spring:
  application:
    name: grpc-client
  sleuth:
    enabled: true
    sampler:
      probability: 1.0F

  zipkin:
    base-url: http://tracing.accounts-internal-stg-cloud.paytm.com

sample:
  zipkin:
    enabled: true

grpc:
  client:
    grpc-server:
      address: static://${server-host}:${server-port}
      negotiationType: plaintext
